### ISSUE TITLE
I have an error and, if it's something you're aware of, wondered if you can help me with a fix?

### ISSUE THREAD

**Issue by nikhil-shrestha** [yardstick17/AspectBasedSentimentAnalysis#2]
PYTHONPATH='.' python3 training/train_top_classifier.py
Traceback (most recent call last):
  File "training/train_top_classifier.py", line 4, in <module>
    import click
ImportError: No module named 'click'

**Comment by yardstick17** [comment]
The error implies the package 'click' is not installed. The package was missing in the requirements.txt. It is updated now. You can take the pull of latest master and run this command.
`pip install -r requirements.txt`
